# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://l0d3.github.io/dapnn/"

git_url = "https://github.com/l0d3/dapnn/tree/{branch}/"

def custom_doc_links(name): return None
